name: nvd cache
on:
  schedule:
    - cron:  '0 11 * * *'
  workflow_dispatch:
  # Needed so we can run it manually

jobs:
  build:
    permissions:
      contents: write
    name: Update NVD API Cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: gh-pages
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
      - name: validate
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          curl -H "Accept: application/json" -H "apiKey: $NVD_API_KEY" -v "https://services.nvd.nist.gov/rest/json/cves/2.0?lastModStartDate=2024-07-06T10%3A15%3A03Z&lastModEndDate=2024-11-03T10%3A15%3A03Z&resultsPerPage=2000&startIndex=0"
      - name: update
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          curl https://github.com/jeremylong/Open-Vulnerability-Project/releases/download/v6.1.3/vulnz-6.1.3.jar -s -L -o vulnz.jar
          git reset --soft HEAD~1
          ls -la .
          java -jar vulnz.jar cve --cache --directory ./nvd_cache  --threads=1 --debug --delay=8000
          rm vulnz.jar
          git status
          cat nvd_cache/cache.properties
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add ./nvd_cache/
          git commit -am 'chore: update'
          git push origin gh-pages --force
